name: Build and Archive ws-scrcpy

on:
 # push:
  #  branches: [ main, master ]
  #pull_request:
  #  branches: [ main, master ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          git clone https://github.com/kasmtech/noVNC.git

      - name: Build Project
        run: cd noVNC && npm install && npm run build


      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: noVNC-dist
          path: |
            noVNC/dist/
